version: '3'
services:
  host-ingress:
    image: traefik:alpine
    networks:
      - network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/acme:/etc/traefik/acme
    restart: unless-stopped

networks:
  network:
    driver: bridge